# Generated by Django 2.2.4 on 2019-09-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='标题', max_length=50)),
                ('date', models.DateField()),
                ('image', models.ImageField(default='default.jpg', upload_to='images/')),
                ('text', models.TextField(default='正文', max_length=5000)),
            ],
        ),
    ]
